-- Creating database and table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE DATABASES;
CREATE TABLE IF NOT EXISTS (id INT UNIQUE AUTO_INCREEMENT NOT NULL, name VARCHAR(256) NOT NULL, PRIMARY KEY(id));
